### ISSUE TITLE
Adapt to smaller width mobile device screens

### ISSUE THREAD

**Issue by heimoshuiyu** [heimoshuiyu/chatgpt-api-web#5]
Although the top status bar has been adjusted to fit narrow-width screens, it is still not sufficient for my phone (or other smaller phones).

![Screenshot_2024-07-19-17-59-17-881_org mozilla firefox](https://github.com/user-attachments/assets/44c7ec4d-3217-4a5a-83a7-3709d5d2eab0)

**Comment by ecwu** [comment]
I am considering remove the session sidebar or at lease not make it persistent at the screen.
Plus:
- Remove the mode from model name annotation, replace it to the second-level drop-down.
- Replace the model name at navbar to session id, since model name can show on top of each bubble.

please share your thought.
